# Generated by Django 2.2.7 on 2019-11-10 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemLocation",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                (
                    "location_type",
                    models.TextField(
                        choices=[
                            ("pantry", "Pantry"),
                            ("fridge", "Fridge"),
                            ("freezer", "Freezer"),
                            ("cart", "Cart"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "user_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_groups.UserGroup",
                    ),
                ),
            ],
            options={"db_table": "item_location", "managed": True,},
        ),
    ]
