# Generated by Django 2.2.7 on 2019-11-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemlocation",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("pantry", "Pantry"),
                    ("fridge", "Fridge"),
                    ("freezer", "Freezer"),
                    ("cart", "Cart"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itemlocation",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
