# Generated by Django 2.2.7 on 2019-11-10 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_groups", "0001_initial"),
        ("item_locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item_location",
            name="loc_type",
            field=models.TextField(
                choices=[
                    ("pantry", "Pantry"),
                    ("fridge", "Fridge"),
                    ("freezer", "Freezer"),
                    ("cart", "Cart"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item_location",
            name="usergrp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_groups.User_Group",
            ),
        ),
    ]
