# Generated by Django 2.2.7 on 2019-11-10 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_definitions", "0002_auto_20191109_2117"),
        ("user_groups", "0002_user_group_user"),
        ("item_adjustments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item_adjustment",
            name="item_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="item_definitions.Item_Definition",
            ),
        ),
        migrations.AddField(
            model_name="item_adjustment",
            name="user_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_groups.User_Group",
            ),
        ),
    ]
