# Generated by Django 2.2.7 on 2019-11-10 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grocery_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemDefinition",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grocery_user.GroceryUser",
                    ),
                ),
            ],
            options={"db_table": "item_definition", "managed": True,},
        ),
        migrations.CreateModel(
            name="ItemSpecification",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("pantry_expiration", models.DurationField(null=True)),
                ("fridge_expiration", models.DurationField(null=True)),
                ("freezer_expiration", models.DurationField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grocery_user.GroceryUser",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item_definitions.ItemDefinition",
                    ),
                ),
            ],
            options={"db_table": "item_specification", "managed": True,},
        ),
    ]
