# Generated by Django 2.2.7 on 2019-11-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_definitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemdefinition",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="itemspecification",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
