# Generated by Django 2.2.7 on 2019-11-10 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_definitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_definition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_definition',
            name='freezer_expiration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='item_definition',
            name='fridge_expiration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='item_definition',
            name='pantry_expiration',
            field=models.DurationField(null=True),
        ),
    ]
