# Generated by Django 2.2.7 on 2019-11-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grocery_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("user", models.ManyToManyField(to="grocery_user.GroceryUser")),
            ],
            options={"db_table": "user_group", "managed": True,},
        ),
    ]
