# Generated by Django 2.2.7 on 2019-11-10 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("user", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "user_group", "managed": True,},
        ),
    ]
