# Generated by Django 2.2.7 on 2019-11-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergroup", name="name", field=models.CharField(max_length=255),
        ),
    ]
