# Generated by Django 2.2.7 on 2019-11-10 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_groups", "0001_initial"),
        ("item_groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("item_definitions", "0001_initial"),
        ("item_locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemAdjustment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                ("note", models.TextField(null=True)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="item_definitions.ItemDefinition",
                    ),
                ),
                (
                    "user_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_groups.UserGroup",
                    ),
                ),
            ],
            options={"db_table": "item_adjustment", "managed": True,},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("expiration_date", models.DateTimeField(null=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "desired_quantity",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "item_group",
                    models.ManyToManyField(blank=True, to="item_groups.ItemGroup"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item_locations.ItemLocation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "static_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="item_definitions.ItemDefinition",
                    ),
                ),
            ],
            options={"db_table": "item", "managed": True,},
        ),
    ]
