# Generated by Django 2.2.7 on 2019-11-10 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item_locations", "0001_initial"),
        ("grocery_user", "0001_initial"),
        ("item_groups", "0001_initial"),
        ("item_definitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("expiration_date", models.DateTimeField(null=True)),
                (
                    "item_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item_locations.ItemLocation",
                    ),
                ),
                ("itemgroup", models.ManyToManyField(to="item_groups.ItemGroup")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grocery_user.GroceryUser",
                    ),
                ),
                (
                    "static_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="item_definitions.ItemDefinition",
                    ),
                ),
            ],
            options={"db_table": "item", "managed": True,},
        ),
    ]
