# Generated by Django 2.2.7 on 2019-11-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='desired_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
