# Generated by Django 2.2.7 on 2019-11-10 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_locations', '0002_auto_20191109_1913'),
        ('item_groups', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expr_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='itmgrp',
            field=models.ManyToManyField(to='item_groups.Item_Group'),
        ),
        migrations.AddField(
            model_name='item',
            name='itmloc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_locations.Item_Location'),
        ),
    ]
