# Generated by Django 2.2.7 on 2019-11-10 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("item_definitions", "0002_auto_20191109_2117"),
        ("items", "0002_auto_20191109_1913"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="expr_date", new_name="expiration_date",
        ),
        migrations.RenameField(
            model_name="item", old_name="itmloc", new_name="item_location",
        ),
        migrations.RenameField(
            model_name="item", old_name="itmgrp", new_name="itemgroup",
        ),
        migrations.AddField(
            model_name="item",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="static_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="item_definitions.Item_Definition",
            ),
        ),
    ]
