# Generated by Django 2.2.7 on 2019-11-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_auto_20191110_0319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemadjustment",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustments",
                to="items.Item",
            ),
        ),
    ]
