# Generated by Django 2.2.7 on 2019-11-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_auto_20191110_0328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item", name="name", field=models.CharField(max_length=255),
        ),
    ]
